const TAG = {
  RESPONSE_USER_ONLINE: "RESPONSE_USER_ONLINE",
  REQUEST_USER_ONLINE: "REQUEST_USER_ONLINE",

  RESPONSE_USER_OFFLINE: "RESPONSE_USER_OFFLINE",
  REQUEST_USER_OFFLINE: "REQUEST_USER_OFFLINE",

  RESPONSE_ROOM_ONLINE: "RESPONSE_ROOM_ONLINE",
  REQUEST_ROOM_ONLINE: "REQUEST_ROOM_ONLINE",

  RESPONSE_ADD_ROOM_ONLINE: "RESPONSE_ADD_ROOM_ONLINE",
  RESPONSE_REMOVE_ROOM_ONLINE: "RESPONSE_REMOVE_ROOM_ONLINE",

  REQUEST_JOIN_ROOM: "REQUEST_JOIN_ROOM",
  REQUEST_LEAVE_ROOM: "REQUEST_LEAVE_ROOM",

  REQUEST_SEND_MESS: "REQUEST_SEND_MESS",
  RESPONSE_SEND_MESS: "RESPONSE_SEND_MESS",

  REQUEST_UPDATE_USER_IN_ROOM: "REQUEST_UPDATE_USER_IN_ROOM",
  RESPONSE_UPDATE_USER_IN_ROOM: "RESPONSE_UPDATE_USER_IN_ROOM",
  RESPONSE_UPDATE_USER_IN_LISTROOM: "RESPONSE_UPDATE_USER_IN_LISTROOM",
};

module.exports = { ...TAG };
