const TAG = {
  RESPONSE_USER_ONLINE: "RESPONSE_USER_ONLINE",
  REQUEST_USER_ONLINE: "REQUEST_USER_ONLINE",

  RESPONSE_USER_OFFLINE: "RESPONSE_USER_OFFLINE",
  REQUEST_USER_OFFLINE: "REQUEST_USER_OFFLINE",

  RESPONSE_ROOM_ONLINE: "RESPONSE_ROOM_ONLINE",
  REQUEST_ROOM_ONLINE: "REQUEST_ROOM_ONLINE",

  RESPONSE_ADD_ROOM_ONLINE: "RESPONSE_ADD_ROOM_ONLINE",
  RESPONSE_REMOVE_ROOM_ONLINE: "RESPONSE_REMOVE_ROOM_ONLINE",
};

module.exports = { ...TAG };
